detect:
  log type: wel
  op: and
  rules:
  - case sensitive: false
    op: is
    path: Event/System/EventID
    value: '5145'
  - case sensitive: false
    op: matches
    path: Event/EventData/ShareName
    re: \\\*\\IPC\$
  - case sensitive: false
    op: is
    path: Event/EventData/RelativeTargetName
    value: spoolss
  - case sensitive: false
    op: is
    path: Event/EventData/AccessMask
    value: '0x3'
  - case sensitive: false
    op: is
    path: Event/EventData/ObjectType
    value: File
  target: log
respond:
- action: report
  metadata:
    author: INIT_6
    description: Detects remote printer driver load from Detailed File Share in Security
      logs that are a sign of successful exploitation attempts against print spooler
      vulnerability CVE-2021-1675 and CVE-2021-34527
    falsepositives:
    - nothing observed so far
    level: critical
    references:
    - https://twitter.com/INIT_3/status/1410662463641731075
    tags:
    - attack.execution
    - attack.t1569
    - cve.2021.1675
    - cve.2021.34527
  name: CVE-2021-1675 Print Spooler Exploitation IPC Access

