detect:
  events:
  - NEW_PROCESS
  - EXISTING_PROCESS
  op: and
  rules:
  - op: is windows
  - op: and
    rules:
    - op: or
      rules:
      - case sensitive: false
        op: ends with
        path: event/FILE_PATH
        value: \regsvr32.exe
      - case sensitive: false
        op: ends with
        path: event/FILE_PATH
        value: \rundll32.exe
      - case sensitive: false
        op: ends with
        path: event/FILE_PATH
        value: \msiexec.exe
      - case sensitive: false
        op: ends with
        path: event/FILE_PATH
        value: \mshta.exe
      - case sensitive: false
        op: ends with
        path: event/FILE_PATH
        value: \verclsid.exe
      - case sensitive: false
        op: ends with
        path: event/FILE_PATH
        value: \msdt.exe
    - op: or
      rules:
      - case sensitive: false
        op: ends with
        path: event/PARENT/FILE_PATH
        value: \winword.exe
      - case sensitive: false
        op: ends with
        path: event/PARENT/FILE_PATH
        value: \excel.exe
      - case sensitive: false
        op: ends with
        path: event/PARENT/FILE_PATH
        value: \powerpnt.exe
      - case sensitive: false
        op: ends with
        path: event/PARENT/FILE_PATH
        value: \msaccess.exe
      - case sensitive: false
        op: ends with
        path: event/PARENT/FILE_PATH
        value: \mspub.exe
      - case sensitive: false
        op: ends with
        path: event/PARENT/FILE_PATH
        value: \eqnedt32.exe
respond:
- action: report
  metadata:
    author: Vadim Khrykov (ThreatIntel), Cyb3rEng (Rule)
    description: This rule will monitor any office apps that spins up a new LOLBin
      process. This activity is pretty suspicious and should be investigated.
    falsepositives:
    - Unknown
    level: high
    references:
    - https://thedfirreport.com/2021/03/29/sodinokibi-aka-revil-ransomware/
    - https://doublepulsar.com/follina-a-microsoft-office-code-execution-vulnerability-1a47fce5629e
    - https://github.com/vadim-hunter/Detection-Ideas-Rules/blob/main/Threat%20Intelligence/The%20DFIR%20Report/20210329_Sodinokibi_(aka_REvil)_Ransomware.yaml
    tags:
    - attack.t1204.002
    - attack.t1047
    - attack.t1218.010
    - attack.execution
    - attack.defense_evasion
  name: New Lolbin Process by Office Applications

