detect:
  events:
  - NEW_PROCESS
  - EXISTING_PROCESS
  op: and
  rules:
  - op: is windows
  - op: and
    rules:
    - case sensitive: false
      op: ends with
      path: event/FILE_PATH
      value: \WMIC.exe
    - case sensitive: false
      op: contains
      path: event/COMMAND_LINE
      value: call uninstall
respond:
- action: report
  metadata:
    author: frac113
    description: Uninstall an application with wmic
    falsepositives:
    - Unknown
    level: medium
    references:
    - https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1047/T1047.md#atomic-test-10---application-uninstall-using-wmic
    tags:
    - attack.execution
    - attack.t1047
  name: WMI Uninstall An Application

