detect:
  events:
  - NEW_PROCESS
  - EXISTING_PROCESS
  op: and
  rules:
  - op: is windows
  - case sensitive: false
    op: ends with
    path: event/FILE_PATH
    value: \ntvdm.exe
respond:
- action: report
  metadata:
    author: frack113
    description: Ntvdm.exe allows the execution of 16-bit Windows applications on
      32-bit Windows operating systems, as well as the execution of both 16-bit and
      32-bit DOS applications
    falsepositives:
    - Legitimate use
    level: medium
    references:
    - https://app.any.run/tasks/93fe92fa-8b2b-4d92-8c09-a841aed2e793/
    - https://docs.microsoft.com/en-us/windows/compatibility/ntvdm-and-16-bit-app-support
    tags:
    - attack.defense_evasion
  name: Start of NT Virtual DOS Machine

