detect:
  log type: wel
  op: and
  rules:
  - case sensitive: false
    op: is
    path: Event/System/EventID
    value: '4698'
  - op: or
    rules:
    - case sensitive: false
      op: is
      path: Event/EventData/TaskName
      value: SC Scheduled Scan
    - case sensitive: false
      op: is
      path: Event/EventData/TaskName
      value: UpdatMachine
  target: log
respond:
- action: report
  metadata:
    author: Florian Roth, Markus Neis, Jonhnathan Ribeiro, Daniil Yugoslavskiy, oscd.community
    description: Detects Chafer activity attributed to OilRig as reported in Nyotron
      report in March 2018
    falsepositives:
    - Unknown
    level: critical
    references:
    - https://nyotron.com/nyotron-discovers-next-generation-oilrig-attacks/
    tags:
    - attack.persistence
    - attack.g0049
    - attack.t1053.005
    - attack.s0111
    - attack.t1543.003
    - attack.defense_evasion
    - attack.t1112
    - attack.command_and_control
    - attack.t1071.004
  name: Chafer Activity - Security

